"""Add Journal

Revision ID: 5bd5f1575ba3
Revises: bf8e5204e833
Create Date: 2020-12-18 13:30:26.821298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd5f1575ba3'
down_revision = 'bf8e5204e833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_info', sa.Integer(), nullable=True),
    sa.Column('time_begin', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('time_total', sa.Integer(), nullable=True),
    sa.Column('cost_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['auto_info'], ['auto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal')
    # ### end Alembic commands ###
