"""Initial migration.

Revision ID: bf8e5204e833
Revises: 
Create Date: 2020-12-17 15:18:03.961535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8e5204e833'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('transmission', sa.String(length=20), nullable=True),
    sa.Column('img_url', sa.String(length=128), nullable=True),
    sa.Column('dostup', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto')
    # ### end Alembic commands ###
